# Generated by Django 4.1.5 on 2023-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stdbio',
            old_name='roll',
            new_name='rollno',
        ),
        migrations.AlterField(
            model_name='stdbio',
            name='address',
            field=models.TextField(),
        ),
    ]
