# Generated by Django 4.1.5 on 2023-02-24 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_rollno_stdbio_roll_stdbio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdbio',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 24, 13, 54, 4, 608396)),
        ),
    ]
