# Generated by Django 4.1.5 on 2023-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_stdbio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdbio',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
