# Generated by Django 4.1.5 on 2023-02-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_stdbio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdbio',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
